package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Alumniview generated by hbm2java
 */
public class Alumniview  implements java.io.Serializable {


     private AlumniviewId id;

    public Alumniview() {
    }

    public Alumniview(AlumniviewId id) {
       this.id = id;
    }
   
    public AlumniviewId getId() {
        return this.id;
    }
    
    public void setId(AlumniviewId id) {
        this.id = id;
    }




}


