package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Jeniskontak generated by hbm2java
 */
public class Jeniskontak  implements java.io.Serializable {


     private Integer idJenisKontak;
     private String jenisKontak;
     private Set kontaks = new HashSet(0);

    public Jeniskontak() {
    }

	
    public Jeniskontak(String jenisKontak) {
        this.jenisKontak = jenisKontak;
    }
    public Jeniskontak(String jenisKontak, Set kontaks) {
       this.jenisKontak = jenisKontak;
       this.kontaks = kontaks;
    }
   
    public Integer getIdJenisKontak() {
        return this.idJenisKontak;
    }
    
    public void setIdJenisKontak(Integer idJenisKontak) {
        this.idJenisKontak = idJenisKontak;
    }
    public String getJenisKontak() {
        return this.jenisKontak;
    }
    
    public void setJenisKontak(String jenisKontak) {
        this.jenisKontak = jenisKontak;
    }
    public Set getKontaks() {
        return this.kontaks;
    }
    
    public void setKontaks(Set kontaks) {
        this.kontaks = kontaks;
    }




}


