package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Kerja generated by hbm2java
 */
public class Kerja  implements java.io.Serializable {


     private Integer idKerja;
     private Jeniskerja jeniskerja;
     private Mahasiswa mahasiswa;
     private Posisikerja posisikerja;
     private String perusahaan;
     private Date tanggalMasuk;
     private Date tanggalKeluar;
     private Integer gaji;
     private Boolean statusKerja;
     private Boolean statusKerjaIndustri;
     private Integer core;

    public Kerja() {
    }

	
    public Kerja(Mahasiswa mahasiswa, String perusahaan) {
        this.mahasiswa = mahasiswa;
        this.perusahaan = perusahaan;
    }
    public Kerja(Jeniskerja jeniskerja, Mahasiswa mahasiswa, Posisikerja posisikerja, String perusahaan, Date tanggalMasuk, Date tanggalKeluar, Integer gaji, Boolean statusKerja, Boolean statusKerjaIndustri, Integer core) {
       this.jeniskerja = jeniskerja;
       this.mahasiswa = mahasiswa;
       this.posisikerja = posisikerja;
       this.perusahaan = perusahaan;
       this.tanggalMasuk = tanggalMasuk;
       this.tanggalKeluar = tanggalKeluar;
       this.gaji = gaji;
       this.statusKerja = statusKerja;
       this.statusKerjaIndustri = statusKerjaIndustri;
       this.core = core;
    }
   
    public Integer getIdKerja() {
        return this.idKerja;
    }
    
    public void setIdKerja(Integer idKerja) {
        this.idKerja = idKerja;
    }
    public Jeniskerja getJeniskerja() {
        return this.jeniskerja;
    }
    
    public void setJeniskerja(Jeniskerja jeniskerja) {
        this.jeniskerja = jeniskerja;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Posisikerja getPosisikerja() {
        return this.posisikerja;
    }
    
    public void setPosisikerja(Posisikerja posisikerja) {
        this.posisikerja = posisikerja;
    }
    public String getPerusahaan() {
        return this.perusahaan;
    }
    
    public void setPerusahaan(String perusahaan) {
        this.perusahaan = perusahaan;
    }
    public Date getTanggalMasuk() {
        return this.tanggalMasuk;
    }
    
    public void setTanggalMasuk(Date tanggalMasuk) {
        this.tanggalMasuk = tanggalMasuk;
    }
    public Date getTanggalKeluar() {
        return this.tanggalKeluar;
    }
    
    public void setTanggalKeluar(Date tanggalKeluar) {
        this.tanggalKeluar = tanggalKeluar;
    }
    public Integer getGaji() {
        return this.gaji;
    }
    
    public void setGaji(Integer gaji) {
        this.gaji = gaji;
    }
    public Boolean getStatusKerja() {
        return this.statusKerja;
    }
    
    public void setStatusKerja(Boolean statusKerja) {
        this.statusKerja = statusKerja;
    }
    public Boolean getStatusKerjaIndustri() {
        return this.statusKerjaIndustri;
    }
    
    public void setStatusKerjaIndustri(Boolean statusKerjaIndustri) {
        this.statusKerjaIndustri = statusKerjaIndustri;
    }
    public Integer getCore() {
        return this.core;
    }
    
    public void setCore(Integer core) {
        this.core = core;
    }




}


