package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Kerjaview generated by hbm2java
 */
public class Kerjaview  implements java.io.Serializable {


     private KerjaviewId id;

    public Kerjaview() {
    }

    public Kerjaview(KerjaviewId id) {
       this.id = id;
    }
   
    public KerjaviewId getId() {
        return this.id;
    }
    
    public void setId(KerjaviewId id) {
        this.id = id;
    }




}


