package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Kontak generated by hbm2java
 */
public class Kontak  implements java.io.Serializable {


     private Integer idKontak;
     private Jeniskontak jeniskontak;
     private Mahasiswa mahasiswa;
     private String kontak;
     private boolean status;

    public Kontak() {
    }

    public Kontak(Jeniskontak jeniskontak, Mahasiswa mahasiswa, String kontak, boolean status) {
       this.jeniskontak = jeniskontak;
       this.mahasiswa = mahasiswa;
       this.kontak = kontak;
       this.status = status;
    }
   
    public Integer getIdKontak() {
        return this.idKontak;
    }
    
    public void setIdKontak(Integer idKontak) {
        this.idKontak = idKontak;
    }
    public Jeniskontak getJeniskontak() {
        return this.jeniskontak;
    }
    
    public void setJeniskontak(Jeniskontak jeniskontak) {
        this.jeniskontak = jeniskontak;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public String getKontak() {
        return this.kontak;
    }
    
    public void setKontak(String kontak) {
        this.kontak = kontak;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


