package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * KontakviewId generated by hbm2java
 */
public class KontakviewId  implements java.io.Serializable {


     private String nim;
     private String nama;
     private String kontak;
     private boolean status;
     private int idJenisKontak;
     private Integer idStatusMahasiswa;

    public KontakviewId() {
    }

	
    public KontakviewId(String nim, String nama, String kontak, boolean status, int idJenisKontak) {
        this.nim = nim;
        this.nama = nama;
        this.kontak = kontak;
        this.status = status;
        this.idJenisKontak = idJenisKontak;
    }
    public KontakviewId(String nim, String nama, String kontak, boolean status, int idJenisKontak, Integer idStatusMahasiswa) {
       this.nim = nim;
       this.nama = nama;
       this.kontak = kontak;
       this.status = status;
       this.idJenisKontak = idJenisKontak;
       this.idStatusMahasiswa = idStatusMahasiswa;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getKontak() {
        return this.kontak;
    }
    
    public void setKontak(String kontak) {
        this.kontak = kontak;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public int getIdJenisKontak() {
        return this.idJenisKontak;
    }
    
    public void setIdJenisKontak(int idJenisKontak) {
        this.idJenisKontak = idJenisKontak;
    }
    public Integer getIdStatusMahasiswa() {
        return this.idStatusMahasiswa;
    }
    
    public void setIdStatusMahasiswa(Integer idStatusMahasiswa) {
        this.idStatusMahasiswa = idStatusMahasiswa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KontakviewId) ) return false;
		 KontakviewId castOther = ( KontakviewId ) other; 
         
		 return ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getNama()==castOther.getNama()) || ( this.getNama()!=null && castOther.getNama()!=null && this.getNama().equals(castOther.getNama()) ) )
 && ( (this.getKontak()==castOther.getKontak()) || ( this.getKontak()!=null && castOther.getKontak()!=null && this.getKontak().equals(castOther.getKontak()) ) )
 && (this.isStatus()==castOther.isStatus())
 && (this.getIdJenisKontak()==castOther.getIdJenisKontak())
 && ( (this.getIdStatusMahasiswa()==castOther.getIdStatusMahasiswa()) || ( this.getIdStatusMahasiswa()!=null && castOther.getIdStatusMahasiswa()!=null && this.getIdStatusMahasiswa().equals(castOther.getIdStatusMahasiswa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getNama() == null ? 0 : this.getNama().hashCode() );
         result = 37 * result + ( getKontak() == null ? 0 : this.getKontak().hashCode() );
         result = 37 * result + (this.isStatus()?1:0);
         result = 37 * result + this.getIdJenisKontak();
         result = 37 * result + ( getIdStatusMahasiswa() == null ? 0 : this.getIdStatusMahasiswa().hashCode() );
         return result;
   }   


}


