package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Kontakview generated by hbm2java
 */
public class Kontakview  implements java.io.Serializable {


     private KontakviewId id;

    public Kontakview() {
    }

    public Kontakview(KontakviewId id) {
       this.id = id;
    }
   
    public KontakviewId getId() {
        return this.id;
    }
    
    public void setId(KontakviewId id) {
        this.id = id;
    }




}


