package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by hbm2java
 */
public class Level  implements java.io.Serializable {


     private Integer idLevel;
     private String nama;
     private Set users = new HashSet(0);

    public Level() {
    }

	
    public Level(String nama) {
        this.nama = nama;
    }
    public Level(String nama, Set users) {
       this.nama = nama;
       this.users = users;
    }
   
    public Integer getIdLevel() {
        return this.idLevel;
    }
    
    public void setIdLevel(Integer idLevel) {
        this.idLevel = idLevel;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


