package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private Peminatan peminatan;
     private User user;
     private Statusmahasiswa statusmahasiswa;
     private Wisuda wisuda;
     private String nama;
     private Date tanggalYudisium;
     private Double ipk;
     private Boolean kontak;
     private String predikat;
     private String sk;
     private Set kontaks = new HashSet(0);
     private Set wirausahas = new HashSet(0);
     private Set kerjas = new HashSet(0);
     private Set studis = new HashSet(0);

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim, User user, String nama) {
        this.nim = nim;
        this.user = user;
        this.nama = nama;
    }
    public Mahasiswa(String nim, Peminatan peminatan, User user, Statusmahasiswa statusmahasiswa, Wisuda wisuda, String nama, Date tanggalYudisium, Double ipk, Boolean kontak, String predikat, String sk, Set kontaks, Set wirausahas, Set kerjas, Set studis) {
       this.nim = nim;
       this.peminatan = peminatan;
       this.user = user;
       this.statusmahasiswa = statusmahasiswa;
       this.wisuda = wisuda;
       this.nama = nama;
       this.tanggalYudisium = tanggalYudisium;
       this.ipk = ipk;
       this.kontak = kontak;
       this.predikat = predikat;
       this.sk = sk;
       this.kontaks = kontaks;
       this.wirausahas = wirausahas;
       this.kerjas = kerjas;
       this.studis = studis;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public Peminatan getPeminatan() {
        return this.peminatan;
    }
    
    public void setPeminatan(Peminatan peminatan) {
        this.peminatan = peminatan;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Statusmahasiswa getStatusmahasiswa() {
        return this.statusmahasiswa;
    }
    
    public void setStatusmahasiswa(Statusmahasiswa statusmahasiswa) {
        this.statusmahasiswa = statusmahasiswa;
    }
    public Wisuda getWisuda() {
        return this.wisuda;
    }
    
    public void setWisuda(Wisuda wisuda) {
        this.wisuda = wisuda;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Date getTanggalYudisium() {
        return this.tanggalYudisium;
    }
    
    public void setTanggalYudisium(Date tanggalYudisium) {
        this.tanggalYudisium = tanggalYudisium;
    }
    public Double getIpk() {
        return this.ipk;
    }
    
    public void setIpk(Double ipk) {
        this.ipk = ipk;
    }
    public Boolean getKontak() {
        return this.kontak;
    }
    
    public void setKontak(Boolean kontak) {
        this.kontak = kontak;
    }
    public String getPredikat() {
        return this.predikat;
    }
    
    public void setPredikat(String predikat) {
        this.predikat = predikat;
    }
    public String getSk() {
        return this.sk;
    }
    
    public void setSk(String sk) {
        this.sk = sk;
    }
    public Set getKontaks() {
        return this.kontaks;
    }
    
    public void setKontaks(Set kontaks) {
        this.kontaks = kontaks;
    }
    public Set getWirausahas() {
        return this.wirausahas;
    }
    
    public void setWirausahas(Set wirausahas) {
        this.wirausahas = wirausahas;
    }
    public Set getKerjas() {
        return this.kerjas;
    }
    
    public void setKerjas(Set kerjas) {
        this.kerjas = kerjas;
    }
    public Set getStudis() {
        return this.studis;
    }
    
    public void setStudis(Set studis) {
        this.studis = studis;
    }




}


