package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Pegawai generated by hbm2java
 */
public class Pegawai  implements java.io.Serializable {


     private String idPegawai;
     private User user;
     private String nama;
     private String telepon;
     private String email;
     private Boolean status;

    public Pegawai() {
    }

	
    public Pegawai(String idPegawai, User user, String nama) {
        this.idPegawai = idPegawai;
        this.user = user;
        this.nama = nama;
    }
    public Pegawai(String idPegawai, User user, String nama, String telepon, String email, Boolean status) {
       this.idPegawai = idPegawai;
       this.user = user;
       this.nama = nama;
       this.telepon = telepon;
       this.email = email;
       this.status = status;
    }
   
    public String getIdPegawai() {
        return this.idPegawai;
    }
    
    public void setIdPegawai(String idPegawai) {
        this.idPegawai = idPegawai;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getTelepon() {
        return this.telepon;
    }
    
    public void setTelepon(String telepon) {
        this.telepon = telepon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


