package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Peminatan generated by hbm2java
 */
public class Peminatan  implements java.io.Serializable {


     private Integer idPeminatan;
     private Prodi prodi;
     private String nama;
     private String inisial;
     private Boolean status;
     private Set mahasiswas = new HashSet(0);

    public Peminatan() {
    }

    public Peminatan(Prodi prodi, String nama, String inisial, Boolean status, Set mahasiswas) {
       this.prodi = prodi;
       this.nama = nama;
       this.inisial = inisial;
       this.status = status;
       this.mahasiswas = mahasiswas;
    }
   
    public Integer getIdPeminatan() {
        return this.idPeminatan;
    }
    
    public void setIdPeminatan(Integer idPeminatan) {
        this.idPeminatan = idPeminatan;
    }
    public Prodi getProdi() {
        return this.prodi;
    }
    
    public void setProdi(Prodi prodi) {
        this.prodi = prodi;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getInisial() {
        return this.inisial;
    }
    
    public void setInisial(String inisial) {
        this.inisial = inisial;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


