package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Posisikerja generated by hbm2java
 */
public class Posisikerja  implements java.io.Serializable {


     private Integer idPosisiKerja;
     private String namaPosisi;
     private Set kerjas = new HashSet(0);

    public Posisikerja() {
    }

	
    public Posisikerja(String namaPosisi) {
        this.namaPosisi = namaPosisi;
    }
    public Posisikerja(String namaPosisi, Set kerjas) {
       this.namaPosisi = namaPosisi;
       this.kerjas = kerjas;
    }
   
    public Integer getIdPosisiKerja() {
        return this.idPosisiKerja;
    }
    
    public void setIdPosisiKerja(Integer idPosisiKerja) {
        this.idPosisiKerja = idPosisiKerja;
    }
    public String getNamaPosisi() {
        return this.namaPosisi;
    }
    
    public void setNamaPosisi(String namaPosisi) {
        this.namaPosisi = namaPosisi;
    }
    public Set getKerjas() {
        return this.kerjas;
    }
    
    public void setKerjas(Set kerjas) {
        this.kerjas = kerjas;
    }




}


