package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Rekapposisialumni generated by hbm2java
 */
public class Rekapposisialumni  implements java.io.Serializable {


     private RekapposisialumniId id;

    public Rekapposisialumni() {
    }

    public Rekapposisialumni(RekapposisialumniId id) {
       this.id = id;
    }
   
    public RekapposisialumniId getId() {
        return this.id;
    }
    
    public void setId(RekapposisialumniId id) {
        this.id = id;
    }




}


