package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Studiview generated by hbm2java
 */
public class Studiview  implements java.io.Serializable {


     private StudiviewId id;

    public Studiview() {
    }

    public Studiview(StudiviewId id) {
       this.id = id;
    }
   
    public StudiviewId getId() {
        return this.id;
    }
    
    public void setId(StudiviewId id) {
        this.id = id;
    }




}


