package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Studi generated by hbm2java
 */
public class Studi  implements java.io.Serializable {


     private Integer idStudi;
     private Mahasiswa mahasiswa;
     private String universitas;
     private String fakultas;
     private String prodi;
     private Date tanggalMasuk;
     private Date tanggalKeluar;
     private Boolean status;
     private Integer core;

    public Studi() {
    }

	
    public Studi(Mahasiswa mahasiswa, String universitas) {
        this.mahasiswa = mahasiswa;
        this.universitas = universitas;
    }
    public Studi(Mahasiswa mahasiswa, String universitas, String fakultas, String prodi, Date tanggalMasuk, Date tanggalKeluar, Boolean status, Integer core) {
       this.mahasiswa = mahasiswa;
       this.universitas = universitas;
       this.fakultas = fakultas;
       this.prodi = prodi;
       this.tanggalMasuk = tanggalMasuk;
       this.tanggalKeluar = tanggalKeluar;
       this.status = status;
       this.core = core;
    }
   
    public Integer getIdStudi() {
        return this.idStudi;
    }
    
    public void setIdStudi(Integer idStudi) {
        this.idStudi = idStudi;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public String getUniversitas() {
        return this.universitas;
    }
    
    public void setUniversitas(String universitas) {
        this.universitas = universitas;
    }
    public String getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(String fakultas) {
        this.fakultas = fakultas;
    }
    public String getProdi() {
        return this.prodi;
    }
    
    public void setProdi(String prodi) {
        this.prodi = prodi;
    }
    public Date getTanggalMasuk() {
        return this.tanggalMasuk;
    }
    
    public void setTanggalMasuk(Date tanggalMasuk) {
        this.tanggalMasuk = tanggalMasuk;
    }
    public Date getTanggalKeluar() {
        return this.tanggalKeluar;
    }
    
    public void setTanggalKeluar(Date tanggalKeluar) {
        this.tanggalKeluar = tanggalKeluar;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Integer getCore() {
        return this.core;
    }
    
    public void setCore(Integer core) {
        this.core = core;
    }




}


