package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Teleponview generated by hbm2java
 */
public class Teleponview  implements java.io.Serializable {


     private TeleponviewId id;

    public Teleponview() {
    }

    public Teleponview(TeleponviewId id) {
       this.id = id;
    }
   
    public TeleponviewId getId() {
        return this.id;
    }
    
    public void setId(TeleponviewId id) {
        this.id = id;
    }




}


