package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * TeleponviewId generated by hbm2java
 */
public class TeleponviewId  implements java.io.Serializable {


     private String nim;
     private String angkatan;
     private String nama;
     private String prodi;
     private String peminatan;
     private String kontak;
     private int idJenisKontak;
     private boolean status;
     private Integer idStatusMahasiswa;
     private String statusMahasiswa;
     private String posisi;
     private String ipk;

    public TeleponviewId() {
    }

	
    public TeleponviewId(String nim, String nama, String prodi, String kontak, int idJenisKontak, boolean status, String statusMahasiswa, String ipk) {
        this.nim = nim;
        this.nama = nama;
        this.prodi = prodi;
        this.kontak = kontak;
        this.idJenisKontak = idJenisKontak;
        this.status = status;
        this.statusMahasiswa = statusMahasiswa;
        this.ipk = ipk;
    }
    public TeleponviewId(String nim, String angkatan, String nama, String prodi, String peminatan, String kontak, int idJenisKontak, boolean status, Integer idStatusMahasiswa, String statusMahasiswa, String posisi, String ipk) {
       this.nim = nim;
       this.angkatan = angkatan;
       this.nama = nama;
       this.prodi = prodi;
       this.peminatan = peminatan;
       this.kontak = kontak;
       this.idJenisKontak = idJenisKontak;
       this.status = status;
       this.idStatusMahasiswa = idStatusMahasiswa;
       this.statusMahasiswa = statusMahasiswa;
       this.posisi = posisi;
       this.ipk = ipk;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(String angkatan) {
        this.angkatan = angkatan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getProdi() {
        return this.prodi;
    }
    
    public void setProdi(String prodi) {
        this.prodi = prodi;
    }
    public String getPeminatan() {
        return this.peminatan;
    }
    
    public void setPeminatan(String peminatan) {
        this.peminatan = peminatan;
    }
    public String getKontak() {
        return this.kontak;
    }
    
    public void setKontak(String kontak) {
        this.kontak = kontak;
    }
    public int getIdJenisKontak() {
        return this.idJenisKontak;
    }
    
    public void setIdJenisKontak(int idJenisKontak) {
        this.idJenisKontak = idJenisKontak;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Integer getIdStatusMahasiswa() {
        return this.idStatusMahasiswa;
    }
    
    public void setIdStatusMahasiswa(Integer idStatusMahasiswa) {
        this.idStatusMahasiswa = idStatusMahasiswa;
    }
    public String getStatusMahasiswa() {
        return this.statusMahasiswa;
    }
    
    public void setStatusMahasiswa(String statusMahasiswa) {
        this.statusMahasiswa = statusMahasiswa;
    }
    public String getPosisi() {
        return this.posisi;
    }
    
    public void setPosisi(String posisi) {
        this.posisi = posisi;
    }
    public String getIpk() {
        return this.ipk;
    }
    
    public void setIpk(String ipk) {
        this.ipk = ipk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeleponviewId) ) return false;
		 TeleponviewId castOther = ( TeleponviewId ) other; 
         
		 return ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getAngkatan()==castOther.getAngkatan()) || ( this.getAngkatan()!=null && castOther.getAngkatan()!=null && this.getAngkatan().equals(castOther.getAngkatan()) ) )
 && ( (this.getNama()==castOther.getNama()) || ( this.getNama()!=null && castOther.getNama()!=null && this.getNama().equals(castOther.getNama()) ) )
 && ( (this.getProdi()==castOther.getProdi()) || ( this.getProdi()!=null && castOther.getProdi()!=null && this.getProdi().equals(castOther.getProdi()) ) )
 && ( (this.getPeminatan()==castOther.getPeminatan()) || ( this.getPeminatan()!=null && castOther.getPeminatan()!=null && this.getPeminatan().equals(castOther.getPeminatan()) ) )
 && ( (this.getKontak()==castOther.getKontak()) || ( this.getKontak()!=null && castOther.getKontak()!=null && this.getKontak().equals(castOther.getKontak()) ) )
 && (this.getIdJenisKontak()==castOther.getIdJenisKontak())
 && (this.isStatus()==castOther.isStatus())
 && ( (this.getIdStatusMahasiswa()==castOther.getIdStatusMahasiswa()) || ( this.getIdStatusMahasiswa()!=null && castOther.getIdStatusMahasiswa()!=null && this.getIdStatusMahasiswa().equals(castOther.getIdStatusMahasiswa()) ) )
 && ( (this.getStatusMahasiswa()==castOther.getStatusMahasiswa()) || ( this.getStatusMahasiswa()!=null && castOther.getStatusMahasiswa()!=null && this.getStatusMahasiswa().equals(castOther.getStatusMahasiswa()) ) )
 && ( (this.getPosisi()==castOther.getPosisi()) || ( this.getPosisi()!=null && castOther.getPosisi()!=null && this.getPosisi().equals(castOther.getPosisi()) ) )
 && ( (this.getIpk()==castOther.getIpk()) || ( this.getIpk()!=null && castOther.getIpk()!=null && this.getIpk().equals(castOther.getIpk()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getAngkatan() == null ? 0 : this.getAngkatan().hashCode() );
         result = 37 * result + ( getNama() == null ? 0 : this.getNama().hashCode() );
         result = 37 * result + ( getProdi() == null ? 0 : this.getProdi().hashCode() );
         result = 37 * result + ( getPeminatan() == null ? 0 : this.getPeminatan().hashCode() );
         result = 37 * result + ( getKontak() == null ? 0 : this.getKontak().hashCode() );
         result = 37 * result + this.getIdJenisKontak();
         result = 37 * result + (this.isStatus()?1:0);
         result = 37 * result + ( getIdStatusMahasiswa() == null ? 0 : this.getIdStatusMahasiswa().hashCode() );
         result = 37 * result + ( getStatusMahasiswa() == null ? 0 : this.getStatusMahasiswa().hashCode() );
         result = 37 * result + ( getPosisi() == null ? 0 : this.getPosisi().hashCode() );
         result = 37 * result + ( getIpk() == null ? 0 : this.getIpk().hashCode() );
         return result;
   }   


}


