package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private Level level;
     private String password;
     private Boolean activeStatus;
     private Date activeSince;
     private Date lastLogin;
     private Set mahasiswas = new HashSet(0);
     private Set pegawais = new HashSet(0);

    public User() {
    }

	
    public User(String username, Level level, String password) {
        this.username = username;
        this.level = level;
        this.password = password;
    }
    public User(String username, Level level, String password, Boolean activeStatus, Date activeSince, Date lastLogin, Set mahasiswas, Set pegawais) {
       this.username = username;
       this.level = level;
       this.password = password;
       this.activeStatus = activeStatus;
       this.activeSince = activeSince;
       this.lastLogin = lastLogin;
       this.mahasiswas = mahasiswas;
       this.pegawais = pegawais;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Level getLevel() {
        return this.level;
    }
    
    public void setLevel(Level level) {
        this.level = level;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Date getActiveSince() {
        return this.activeSince;
    }
    
    public void setActiveSince(Date activeSince) {
        this.activeSince = activeSince;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }
    public Set getPegawais() {
        return this.pegawais;
    }
    
    public void setPegawais(Set pegawais) {
        this.pegawais = pegawais;
    }




}


