package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WirausahaviewId generated by hbm2java
 */
public class WirausahaviewId  implements java.io.Serializable {


     private String nim;
     private Date tanggalMulai;
     private Integer core;

    public WirausahaviewId() {
    }

	
    public WirausahaviewId(String nim, Date tanggalMulai) {
        this.nim = nim;
        this.tanggalMulai = tanggalMulai;
    }
    public WirausahaviewId(String nim, Date tanggalMulai, Integer core) {
       this.nim = nim;
       this.tanggalMulai = tanggalMulai;
       this.core = core;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public Date getTanggalMulai() {
        return this.tanggalMulai;
    }
    
    public void setTanggalMulai(Date tanggalMulai) {
        this.tanggalMulai = tanggalMulai;
    }
    public Integer getCore() {
        return this.core;
    }
    
    public void setCore(Integer core) {
        this.core = core;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WirausahaviewId) ) return false;
		 WirausahaviewId castOther = ( WirausahaviewId ) other; 
         
		 return ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getTanggalMulai()==castOther.getTanggalMulai()) || ( this.getTanggalMulai()!=null && castOther.getTanggalMulai()!=null && this.getTanggalMulai().equals(castOther.getTanggalMulai()) ) )
 && ( (this.getCore()==castOther.getCore()) || ( this.getCore()!=null && castOther.getCore()!=null && this.getCore().equals(castOther.getCore()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getTanggalMulai() == null ? 0 : this.getTanggalMulai().hashCode() );
         result = 37 * result + ( getCore() == null ? 0 : this.getCore().hashCode() );
         return result;
   }   


}


