package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA



/**
 * Wirausahaview generated by hbm2java
 */
public class Wirausahaview  implements java.io.Serializable {


     private WirausahaviewId id;

    public Wirausahaview() {
    }

    public Wirausahaview(WirausahaviewId id) {
       this.id = id;
    }
   
    public WirausahaviewId getId() {
        return this.id;
    }
    
    public void setId(WirausahaviewId id) {
        this.id = id;
    }




}


