package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Wirausaha generated by hbm2java
 */
public class Wirausaha  implements java.io.Serializable {


     private Integer idWirausaha;
     private Mahasiswa mahasiswa;
     private String namaPerusahaan;
     private String jenisUsaha;
     private Date tanggalMulai;
     private Boolean status;
     private Integer core;

    public Wirausaha() {
    }

	
    public Wirausaha(Mahasiswa mahasiswa, String namaPerusahaan) {
        this.mahasiswa = mahasiswa;
        this.namaPerusahaan = namaPerusahaan;
    }
    public Wirausaha(Mahasiswa mahasiswa, String namaPerusahaan, String jenisUsaha, Date tanggalMulai, Boolean status, Integer core) {
       this.mahasiswa = mahasiswa;
       this.namaPerusahaan = namaPerusahaan;
       this.jenisUsaha = jenisUsaha;
       this.tanggalMulai = tanggalMulai;
       this.status = status;
       this.core = core;
    }
   
    public Integer getIdWirausaha() {
        return this.idWirausaha;
    }
    
    public void setIdWirausaha(Integer idWirausaha) {
        this.idWirausaha = idWirausaha;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public String getNamaPerusahaan() {
        return this.namaPerusahaan;
    }
    
    public void setNamaPerusahaan(String namaPerusahaan) {
        this.namaPerusahaan = namaPerusahaan;
    }
    public String getJenisUsaha() {
        return this.jenisUsaha;
    }
    
    public void setJenisUsaha(String jenisUsaha) {
        this.jenisUsaha = jenisUsaha;
    }
    public Date getTanggalMulai() {
        return this.tanggalMulai;
    }
    
    public void setTanggalMulai(Date tanggalMulai) {
        this.tanggalMulai = tanggalMulai;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Integer getCore() {
        return this.core;
    }
    
    public void setCore(Integer core) {
        this.core = core;
    }




}


