package Model;
// Generated 19 Agu 13 5:20:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Wisuda generated by hbm2java
 */
public class Wisuda  implements java.io.Serializable {


     private Integer idWisuda;
     private String periode;
     private Date tanggal;
     private String keterangan;
     private Set mahasiswas = new HashSet(0);

    public Wisuda() {
    }

	
    public Wisuda(String periode, Date tanggal, String keterangan) {
        this.periode = periode;
        this.tanggal = tanggal;
        this.keterangan = keterangan;
    }
    public Wisuda(String periode, Date tanggal, String keterangan, Set mahasiswas) {
       this.periode = periode;
       this.tanggal = tanggal;
       this.keterangan = keterangan;
       this.mahasiswas = mahasiswas;
    }
   
    public Integer getIdWisuda() {
        return this.idWisuda;
    }
    
    public void setIdWisuda(Integer idWisuda) {
        this.idWisuda = idWisuda;
    }
    public String getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(String periode) {
        this.periode = periode;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


